# Generated by Django 3.2.8 on 2021-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogoPedia_App', '0002_alter_users_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
