races = ('Kundelek', 'Aidi', 'Airedale terrier', 'Akita amerykańska', 'Akita Inu', 'Alaskan malamute',
         'Alpejski gończy krótkonożny', 'American staffordshire terrier', 'Anatolian', 'Appenzeller',
         'Ariegeois', 'Australian cattle dog', 'Australian silky terrier', 'Barbet', 'Basenji',
         'Basset artezyjsko-normandzki', 'Basset bretoński', 'Basset hound', 'Beagle', 'Beagle-harrier',
         'Bearded collie', 'Bedlington terrier', 'Bergamasco', 'Bernardyn', 'Berneński pies pasterski',
         'Biały owczarek szwajcarski', 'Bichon frise', 'Billy', 'Black and tan coonhound', 'Bloodhound',
         'Boerboel', 'Bokser', 'Bolończyk', 'Border collie', 'Border terrier', 'Boston terrier', 'Bouvier des Ardennes',
         'Bouvier des Flandres', 'Brabantczyk', 'Braque d\'Auvergne', 'Braque de l\'Ariege', 'Bohund norweski',
         'Buldog amerykański', 'Buldog angielski', 'Buldog francuski', 'Bullmastif', 'Bulterier', 'Bulterier miniaturowy',
         'Cairn terrier', 'Canaan dog', 'Cane corso', 'Cao fila de Sao Miguel', 'Cavalier king charles spaniel',
         'Charcik włoski', 'Chart afgański', 'Chart afrykański', 'Chart arabski', 'Chart hiszpański', 'Chart perski',
         'Chart polski', 'Chart rosyjski borzoj', 'Chart szkocki', 'Chart węgierski', 'Chesapeake bay retriever',
         'Chien d\'Artois', 'Chihuahua', 'Chin japoński', 'Chow chow', 'Cirneco Dell\'Etna', 'Clumber spaniel',
         'Cocker spaniel amerykański', 'Cocker spaniel amerykański', 'Coton de Tulear', 'Curly coated retriever',
         'Cursinu', 'Czarnogórski gończy górski', 'Czarny terier rosyjski', 'Czeski fousek', 'Czuwacz słowacki',
         'Dalmatyńczyk', 'Dandie dinmont terrier', 'Doberman', 'Dog argentyński', 'Dog kanaryjski', 'Dog niemiecki',
         'Dog z Majorki', 'Dogue de Bordeaux', 'Drentse patrijshond', 'Drever', 'Dunker',
         'Duży gończy anglo-francuski biało-czarny', 'Duży gończy anglo-francuski biało-pomarańczowy',
         'Duży gończy anglo-francuski trójkolorowy', 'Duży munsterlander', 'Duży szwajcarski pies pasterski',
         'Elkhund szary', 'English toy terrier', 'Entlebucher', 'Eurasier', 'Field spaniel', 'Fila brasiliero',
         'Fiński lapphund', 'Flat coated retriever', 'Foksterier', 'Foxhound amerykański', 'Foxhound angielski',
         'Fryzyjski pies dowodny', 'Gascon saintongeois', 'Golden retriever', 'Gończy austriacki', 'Gończy bałkański',
         'Gończy bośniacki szorstkowłosy', 'Gończy bretoński', 'Gończy chorwacki', 'Gończy fiński',
         'Gończy francuski biało-czarny', 'Gończy francuski biało-pomarańczowy', 'Gończy francuski trójkolorowy',
         'Gończy gaskoński', 'Gończy grecki', 'Gończy Hamiltona', 'Gończy hiszpański', 'Gończy istryjski krótkowłosy',
         'Gończy istryjski szorstkowłosy', 'Gończy niemiecki', 'Gończy polski', 'Gończy Schillera',
         'Gończy serbski trójkolorowy', 'Gończy słowacki', 'Gończy smalandzki', 'Gończy styryjski', 'Gończy szwajcarski',
         'Gończy szwajcarski krótkonożny', 'Gończy tyrolski', 'Gończy węgierski', 'Gończy włoski',
         'Grand basset griffon vendeen', 'Grand griffon vendeen', 'Greyhound', 'Gryfon Korthalsa', 'Gryfonik belgijski',
         'Gryfonik brukselski', 'Grzywacz chiński', 'Haldenstovare', 'Harrier', 'Hawańczyk', 'Hiszpański pies dowodny',
         'Hokkaido', 'Hollandse Smoushond', 'Hovawart', 'Husky syberyjski', 'Hygenhund', 'Irish Glen of Imaal Terrier',
         'Irish soft coated wheaten terrier', 'Irlandzki spaniel dowodny', 'Islandzki szpic pasterski',
         'Jack russel terrier', 'Jamnik', 'Jamthund', 'Jindo', 'Kai', 'Karelski pies niedźwiedzie', 'Kelpie',
         'Kerry blue terier', 'King charles spaniel', 'Kishu', 'Komondor', 'Kooikerhondje (płochacz holenderski)',
         'Kromfohrlander', 'Kuvasz', 'Labrador retriever', 'Lagotto romagnolo', 'Lakeland terier', 'Landseer',
         'Lapinporokoira (lapoński pies pasterski)', 'Leonberger', 'Lhasa apso', 'Lwi piesek',
         'Łajka rosyjsko-europejska', 'Łajka zachodniosyberyjska', 'Maltańczyk (bichon maltański)',
         'Mały gończy anglo-francuski', 'Mały munsterlander', 'Manchester terrier', 'Mastif angielski',
         'Mastif hiszpański', 'Mastif neapolitański', 'Mastif pirenejski', 'Mastif tybetański', 'Mops', 'Mudi',
         'Nagi pies meksykański', 'Nagi pies peruwiański', 'Niemiecki terier myśliwski', 'Norfolk/Norwich terrier',
         'Norsk lundehund', 'Nowofundland', 'Ogar polski', 'Otterhound', 'Owczarek australijski', 'Owczarek belgijski',
         'Owczarek chorwacki', 'Owczarek francuski beauceron', 'Owczarek francuski briard', 'Owczarek holenderski',
         'Owczarek kataloński', 'Owczarek kaukaski', 'Owczarek kraski', 'Owczarek Maremma', 'Owczarek niemiecki',
         'Owczarek pikardyjski', 'Owczarek podhalański', 'Owczarek południoworosyjski jużak', 'Owczarek portugalski',
         'Owczarek środkowoazjatycki', 'Owczarek staroangielski bobtail', 'Owczarek szetlandzki',
         'Owczarek szkocki długowłosy', 'Owczarek szkocki krótkowłosy', 'Owczarek z Majorki', 'Parson russell terrier',
         'Pekińczyk', 'Petit basset griffon vendeen', 'Petit gascon saintongeois', 'Pies faraona',
         'Pies górski z Estrela', 'Pies grenlandzki', 'Pies tajwański', 'Pies z Castro Laboreiro', 'Pinczer austriacki',
         'Pinczer małpi', 'Pinczer miniaturowy', 'Pinczer średni', 'Pirenejski pies górski', 'Płochacz niemiecki',
         'Podenco kanaryjski', 'Podenco z Ibizy', 'Podengo portugalski', 'Pointer', 'Poitevin',
         'Polski owczarek nizinny', 'Porcelaine', 'Portugalski pies dowodny', 'Portugalski pies stróżujący',
         'Posokowiec bawarski', 'Posokowiec hanowerski', 'Pudel', 'Pudelpointer', 'Puli', 'Pumi',
         'Retriever z Nowej Szkocji (Toller)', 'Rhodesian ridgeback', 'Rosyjski toy', 'Rottweiler', 'Saarlooswolfhond',
         'Samojed', 'Sarplaninac', 'Schapendoes', 'Schipperke', 'Sealyham terrier', 'Seter angielski', 'Seter irlandzki',
         'Seter irlandzki czerwono-biały', 'Seter szkocki gordon', 'Shar pei', 'Shiba Inu', 'Shih tzu', 'Shikoku',
         'Skye terrier', 'Spaniel bretoński', 'Spaniel francuski', 'Spaniel kontynentalny papillon',
         'Spaniel pikardyjski', 'Spaniel Pont-Audemer', 'Spaniel tybetański', 'Springer spaniel angielski',
         'Springer spaniel walijski', 'Staffordshire bull terrier', 'Sussex spaniel', 'Sznaucer minuaturowy',
         'Sznaucer olbrzymi', 'Sznaucer średni', 'Szpic fiński', 'Szpic japoński', 'Szpic miniaturowy (pomeranian)',
         'Szpic niemiecki', 'Szpic nordycki', 'Szpic wilczy', 'Szpic włoski', 'Szwedzki lapphund', 'Terier australijski',
         'Terier brazylijski', 'Terier czeski', 'Terier irlandzki', 'Terier japoński', 'Terier szkocki',
         'Terier tybetański', 'Terier walijski', 'Thai ridgeback', 'Tornjak', 'Tosa', 'Vastgotaspets',
         'Welsh corgi pembroke', 'West highland white rerrier', 'Westfalski gończy krótkonożny', 'Whippet',
         'Wilczak czechosłowacki', 'Wilczarz irlandzki', 'Wyżeł duński', 'Wyżeł francuski', 'Wyżeł fryzyjski',
         'Wyżeł hiszpański z Burgos', 'Wyżeł niemiecki długowłosy', 'Wyżeł niemiecki krótkowłosy',
         'Wyżeł niemiecki ostrowłosy', 'Wyżeł niemiecki szorstkowłosy', 'Wyżeł portugalski',
         'Wyżeł słowacki szorstkowłosy', 'Wyżeł węgierski', 'Wyżeł weimarski', 'Wyżeł włoski krótkowłosy',
         'Wyżeł włoski szorstkowłosy', 'Yorkshire terrier')